import type { Brand, HistoryEvent, OwnershipEvent, Vehicle } from "./types";

export const BRANDS: Brand[] = [
  {
    slug: "mercedes",
    name: "Mercedes-Benz",
    fullName: "Mercedes-Benz",
    logoUrl: "/images/brands/mercedes-logo.png",
    tagline: "Das Beste oder nichts",
    description:
      "From the hand-built elegance of the 190SL to the Pagoda era and the long reign of the R107, the Mercedes-Benz wing of the collection traces four decades of Stuttgart's open-top grand touring tradition.",
  },
  {
    slug: "porsche",
    name: "Porsche",
    fullName: "Dr. Ing. h.c. F. Porsche AG",
    logoUrl: "/images/brands/porsche-logo.png",
    tagline: "There is no substitute",
    description:
      "Sixty years of Porsche engineering — from the air-cooled purity of the 356 and the brutal 930 Turbo to the modern apex of the GT4 RS and Turbo S.",
  },
  {
    slug: "ferrari",
    name: "Ferrari",
    fullName: "Ferrari S.p.A.",
    logoUrl: "/images/brands/ferrari-logo.png",
    tagline: "We are the competition",
    description:
      "Maranello's final naturally-aspirated V8 spider — a 9,000 rpm farewell to one of the greatest engines Ferrari ever built.",
  },
];

const OWNER = "The Lara Collection";
const LOCATION = "Private Climate-Controlled Facility";

function ownership(
  vehicleId: string,
  events: Array<{ label: string; detail?: string; date: string }>
): OwnershipEvent[] {
  return events.map((e, i) => ({
    id: `${vehicleId}-own-${i}`,
    vehicleId,
    label: e.label,
    detail: e.detail ?? null,
    date: e.date,
    sortOrder: i,
  }));
}

function history(
  vehicleId: string,
  events: Array<{
    date: string;
    type: HistoryEvent["type"];
    title: string;
    detail?: string;
    severity?: HistoryEvent["severity"];
    mileage?: number;
    source?: string;
  }>
): HistoryEvent[] {
  return events.map((e, i) => ({
    id: `${vehicleId}-hist-${i}`,
    vehicleId,
    date: e.date,
    type: e.type,
    severity: e.severity ?? null,
    title: e.title,
    detail: e.detail ?? null,
    mileage: e.mileage ?? null,
    source: e.source ?? null,
    sortOrder: i,
  }));
}

type VehicleSeed = Omit<
  Vehicle,
  | "images"
  | "videos"
  | "documents"
  | "serviceRecords"
  | "ownershipHistory"
  | "historyEvents"
  | "engineSoundUrl"
> & {
  ownershipHistory?: OwnershipEvent[];
  historyEvents?: HistoryEvent[];
  engineSoundUrl?: string | null;
};

function vehicle(v: VehicleSeed): Vehicle {
  return {
    ...v,
    engineSoundUrl: v.engineSoundUrl ?? null,
    historyEvents:
      v.historyEvents ??
      history(v.id, [
        {
          date: String(v.year),
          type: "sale",
          title: "Sold new",
          detail: "Original retail delivery",
          source: "Factory records",
        },
        {
          date: String(v.year),
          type: "title",
          title: `Title issued — ${v.titleStatus}`,
          source: "DMV records",
        },
        ...(v.purchaseDate
          ? [
              {
                date: v.purchaseDate,
                type: "sale" as const,
                title: "Acquired by The Lara Collection",
                detail: "Current ownership",
                mileage: v.mileage,
                source: "Collection records",
              },
            ]
          : []),
      ]),
    images: [],
    videos: v.rotatingVideoUrl
      ? [
          {
            id: `${v.id}-vid-0`,
            vehicleId: v.id,
            url: v.rotatingVideoUrl,
            kind: "rotating",
            title: `${v.year} ${v.make} ${v.model} — Studio Rotation`,
          },
        ]
      : [],
    documents: [],
    serviceRecords: [],
    ownershipHistory:
      v.ownershipHistory ??
      ownership(v.id, [
        { label: "Manufactured", date: String(v.year) },
        { label: "First Owner", detail: "Original delivery", date: String(v.year) },
        {
          label: "Acquired by The Lara Collection",
          detail: "Current ownership",
          date: v.purchaseDate ?? "—",
        },
      ]),
  };
}

export const SEED_VEHICLES: Vehicle[] = [
  // ───────────────────────── MERCEDES-BENZ ─────────────────────────
  vehicle({
    id: "v-190sl-1958",
    slug: "1958-mercedes-benz-190sl",
    brand: "mercedes",
    year: 1958,
    make: "Mercedes-Benz",
    model: "190SL",
    chassisCode: "W121",
    vin: "121040-10-85XXXXX",
    color: "Silver Grey Metallic",
    interiorColor: "Red Leather",
    mileage: 68420,
    currentOwner: OWNER,
    purchaseDate: "2012-06-14",
    purchasePrice: 92000,
    estimatedValue: 165000,
    numOwners: 4,
    titleStatus: "Clean",
    carfaxStatus: "Pre-Carfax Era — Documented History",
    location: LOCATION,
    story: `The 190SL is where this collection begins — chronologically and spiritually. Unveiled at the 1954 New York Auto Show beside its racing sibling, the 300SL, the 190SL offered the same long-hood elegance with a temperament built for the boulevard rather than the Mille Miglia.

This 1958 example left the Sindelfingen works in Silver Grey over red leather, a combination that has never been changed. It spent its first three decades in California, where the dry climate preserved its original floors and inner fenders. A four-year, photo-documented restoration was completed before it joined the collection in 2012.

It remains the car the collection drives slowest — and looks at longest.`,
    rotatingVideoUrl: "/videos/1958-mercedes-benz-190sl-rotating.mp4",
    heroImageUrl: null,
    engineSoundUrl: "/audio/1958-mercedes-benz-190sl-engine.mp4",
    featured: true,
    featuredOrder: 1,
    engine: "1.9L M121 Inline-4",
    transmission: "4-Speed Manual",
    horsepower: 104,
    torque: "105 lb-ft",
    drivetrain: "RWD",
    topSpeed: "106 mph",
    zeroToSixty: "13.5 s",
    fuelType: "Gasoline",
    bodyStyle: "Roadster",
    productionNumbers: "25,881 (1955–1963)",
    marketValue: "$140,000 – $190,000",
    ownershipHistory: ownership("v-190sl-1958", [
      { label: "Manufactured", detail: "Sindelfingen, West Germany", date: "1958" },
      { label: "First Owner", detail: "Delivered new, Los Angeles, CA", date: "1958" },
      { label: "Second Owner", detail: "Pasadena, CA", date: "1971" },
      { label: "Restoration Completed", detail: "Body-off, photo-documented", date: "2009" },
      { label: "Acquired by The Lara Collection", date: "2012-06-14" },
    ]),
    historyEvents: history("v-190sl-1958", [
      { date: "1958", type: "sale", title: "Sold new", detail: "Delivered new, Los Angeles, CA", source: "Factory data card" },
      { date: "1958", type: "title", title: "Title issued — Clean", detail: "California", source: "DMV records" },
      { date: "1971", type: "sale", title: "Second owner", detail: "Private sale, Pasadena, CA", source: "Documented history" },
      { date: "2005", type: "service", title: "Restoration begun", detail: "Body-off, four-year photo-documented restoration", source: "Restoration file" },
      { date: "2009", type: "service", title: "Restoration completed", detail: "Original floors and inner fenders retained; Solex carburetors rebuilt", source: "Restoration file" },
      { date: "2012-06-14", type: "sale", title: "Acquired by The Lara Collection", detail: "Current ownership", mileage: 66800, source: "Collection records" },
      { date: "2024-04-10", type: "inspection", title: "Concours inspection passed", detail: "No accident damage, no rust repair found anywhere on the structure", mileage: 68420, source: "Independent appraiser" },
    ]),
  }),
  vehicle({
    id: "v-230sl-1965",
    slug: "1965-mercedes-benz-230sl",
    brand: "mercedes",
    year: 1965,
    make: "Mercedes-Benz",
    model: "230SL",
    chassisCode: "W113",
    vin: "113042-10-01XXXXX",
    color: "White (DB 050)",
    interiorColor: "Cognac MB-Tex",
    mileage: 81250,
    currentOwner: OWNER,
    purchaseDate: "2015-03-20",
    purchasePrice: 58000,
    estimatedValue: 95000,
    numOwners: 5,
    titleStatus: "Clean",
    carfaxStatus: "Pre-Carfax Era — Documented History",
    location: LOCATION,
    story: `Paul Bracq's "Pagoda" roof made the W113 an instant icon — a concave hardtop that was stronger, lighter, and more graceful than anything else on the road in 1963. The 230SL was the first of the line, and many collectors still consider it the purest.

This 1965 car is a matching-numbers example in white over cognac, fitted with both its soft top and the original pagoda hardtop. It was sold new in Frankfurt, exported to the United States in the 1980s, and has been maintained on a strict schedule ever since.`,
    rotatingVideoUrl: null,
    heroImageUrl: null,
    featured: false,
    featuredOrder: null,
    engine: "2.3L M127 Inline-6",
    transmission: "4-Speed Manual",
    horsepower: 148,
    torque: "145 lb-ft",
    drivetrain: "RWD",
    topSpeed: "124 mph",
    zeroToSixty: "9.7 s",
    fuelType: "Gasoline",
    bodyStyle: "Roadster",
    productionNumbers: "19,831 (1963–1967)",
    marketValue: "$80,000 – $110,000",
    historyEvents: history("v-230sl-1965", [
      { date: "1965", type: "sale", title: "Sold new", detail: "Delivered new, Frankfurt, West Germany", source: "Factory data card" },
      { date: "1983", type: "registration", title: "Exported to the United States", detail: "Registered in New Jersey", source: "Import records" },
      { date: "1989", type: "accident", severity: "minor", title: "Minor accident reported", detail: "Left front fender damage in a parking incident. Fender repaired and refinished to factory standard; no structural involvement.", mileage: 54200, source: "Insurance record" },
      { date: "1990", type: "service", title: "Repair completed", detail: "Fender refinish in original DB 050 White, documented with invoices", source: "Body shop invoice" },
      { date: "2015-03-20", type: "sale", title: "Acquired by The Lara Collection", detail: "Current ownership", mileage: 78900, source: "Collection records" },
      { date: "2023-09-02", type: "service", title: "Major service", detail: "Injection pump rebuilt, cooling system overhauled", mileage: 80700, source: "Service file" },
    ]),
  }),
  vehicle({
    id: "v-230sl-1966",
    slug: "1966-mercedes-benz-230sl",
    brand: "mercedes",
    year: 1966,
    make: "Mercedes-Benz",
    model: "230SL",
    chassisCode: "W113",
    vin: "113042-10-02XXXXX",
    color: "Anthracite Grey",
    interiorColor: "Black Leather",
    mileage: 73900,
    currentOwner: OWNER,
    purchaseDate: "2017-09-08",
    purchasePrice: 64000,
    estimatedValue: 98000,
    numOwners: 3,
    titleStatus: "Clean",
    carfaxStatus: "Pre-Carfax Era — Documented History",
    location: LOCATION,
    story: `A second Pagoda — because one was never going to be enough. Where the 1965 car is the collection's sunny-day tourer, this 1966 230SL in Anthracite over black is its more serious twin: an unrestored, three-owner car wearing much of its original paint.

The car retains its original data card, books, and tool roll. It is preserved rather than restored, and the collection intends to keep it that way.`,
    rotatingVideoUrl: null,
    heroImageUrl: null,
    featured: false,
    featuredOrder: null,
    engine: "2.3L M127 Inline-6",
    transmission: "4-Speed Automatic",
    horsepower: 148,
    torque: "145 lb-ft",
    drivetrain: "RWD",
    topSpeed: "121 mph",
    zeroToSixty: "10.2 s",
    fuelType: "Gasoline",
    bodyStyle: "Roadster",
    productionNumbers: "19,831 (1963–1967)",
    marketValue: "$85,000 – $115,000",
  }),
  vehicle({
    id: "v-250sl-1967",
    slug: "1967-mercedes-benz-250sl",
    brand: "mercedes",
    year: 1967,
    make: "Mercedes-Benz",
    model: "250SL",
    chassisCode: "W113",
    vin: "113043-10-00XXXXX",
    color: "Tobacco Brown",
    interiorColor: "Parchment Leather",
    mileage: 88700,
    currentOwner: OWNER,
    purchaseDate: "2018-11-02",
    purchasePrice: 71000,
    estimatedValue: 105000,
    numOwners: 4,
    titleStatus: "Clean",
    carfaxStatus: "Pre-Carfax Era — Documented History",
    location: LOCATION,
    story: `The 250SL is the rarest of the Pagodas — a single-year model built only for 1967 while Stuttgart prepared the 280SL. It paired the 230SL's revvy character with a larger 2.5-litre six, four-wheel disc brakes, and a larger fuel tank.

Only 5,196 were built. This one, in unusual Tobacco Brown over parchment, is a European-delivery car with the desirable ZF 5-speed conversion documented and reversible — the original gearbox travels with the car.`,
    rotatingVideoUrl: null,
    heroImageUrl: null,
    featured: false,
    featuredOrder: null,
    engine: "2.5L M129 Inline-6",
    transmission: "4-Speed Manual",
    horsepower: 150,
    torque: "159 lb-ft",
    drivetrain: "RWD",
    topSpeed: "121 mph",
    zeroToSixty: "9.5 s",
    fuelType: "Gasoline",
    bodyStyle: "Roadster",
    productionNumbers: "5,196 (1966–1968)",
    marketValue: "$90,000 – $125,000",
  }),
  vehicle({
    id: "v-280sl-1969",
    slug: "1969-mercedes-benz-280sl",
    brand: "mercedes",
    year: 1969,
    make: "Mercedes-Benz",
    model: "280SL",
    chassisCode: "W113",
    vin: "113044-10-01XXXXX",
    color: "Midnight Blue",
    interiorColor: "Grey Leather",
    mileage: 64300,
    currentOwner: OWNER,
    purchaseDate: "2014-05-17",
    purchasePrice: 86000,
    estimatedValue: 135000,
    numOwners: 4,
    titleStatus: "Clean",
    carfaxStatus: "Pre-Carfax Era — Documented History",
    location: LOCATION,
    story: `The 280SL is the Pagoda fully realized — the 2.8-litre M130 six gave the W113 the torque its elegance always promised. It is the version that ended up in the hands of architects, actors, and anyone else with impeccable taste in 1969.

This Midnight Blue example completes the collection's Pagoda set: every engine displacement of the W113 line, 230, 250 and 280, sits under one roof. It is the most driven of the four.`,
    rotatingVideoUrl: null,
    heroImageUrl: null,
    featured: false,
    featuredOrder: null,
    engine: "2.8L M130 Inline-6",
    transmission: "4-Speed Automatic",
    horsepower: 168,
    torque: "177 lb-ft",
    drivetrain: "RWD",
    topSpeed: "124 mph",
    zeroToSixty: "9.3 s",
    fuelType: "Gasoline",
    bodyStyle: "Roadster",
    productionNumbers: "23,885 (1967–1971)",
    marketValue: "$110,000 – $160,000",
  }),
  vehicle({
    id: "v-280slc-1970",
    slug: "1970-mercedes-benz-280slc",
    brand: "mercedes",
    year: 1970,
    make: "Mercedes-Benz",
    model: "280SLC",
    chassisCode: "W113",
    vin: "113044-12-00XXXXX",
    color: "Dark Olive",
    interiorColor: "Cognac Leather",
    mileage: 91100,
    currentOwner: OWNER,
    purchaseDate: "2019-07-25",
    purchasePrice: 67000,
    estimatedValue: 96000,
    numOwners: 5,
    titleStatus: "Clean",
    carfaxStatus: "Pre-Carfax Era — Documented History",
    location: LOCATION,
    story: `An unusual car with an unusual designation — this 1970 280SLC is a late-production W113 delivered with the factory hardtop and the rare "California Coupe" configuration: hardtop fitted, soft top deleted, and a fold-down rear bench in its place.

Dark Olive over cognac is a combination rarely seen on the Pagoda, and it suits the car's quieter, grand-touring character. It is the collection's favourite long-distance classic.`,
    rotatingVideoUrl: null,
    heroImageUrl: null,
    featured: false,
    featuredOrder: null,
    engine: "2.8L M130 Inline-6",
    transmission: "4-Speed Automatic",
    horsepower: 168,
    torque: "177 lb-ft",
    drivetrain: "RWD",
    topSpeed: "124 mph",
    zeroToSixty: "9.6 s",
    fuelType: "Gasoline",
    bodyStyle: "Coupe",
    productionNumbers: "Limited California Coupe production",
    marketValue: "$85,000 – $115,000",
  }),
  vehicle({
    id: "v-450sl-1978",
    slug: "1978-mercedes-benz-450sl",
    brand: "mercedes",
    year: 1978,
    make: "Mercedes-Benz",
    model: "450SL",
    chassisCode: "R107",
    vin: "10704412XXXXXX",
    color: "Icon Gold",
    interiorColor: "Bamboo MB-Tex",
    mileage: 102400,
    currentOwner: OWNER,
    purchaseDate: "2016-02-11",
    purchasePrice: 18500,
    estimatedValue: 38000,
    numOwners: 3,
    titleStatus: "Clean",
    carfaxStatus: "Clean — No Accidents Reported",
    location: LOCATION,
    story: `The R107 ran for eighteen years — the longest-serving SL of all — and the 450SL was its 1970s heart. V8 torque, a removable hardtop, and styling that needed no update for nearly two decades.

This Icon Gold car is a two-family example from Arizona with original paint on most panels. It wears its miles honestly and starts on the first turn of the key, every time.`,
    rotatingVideoUrl: null,
    heroImageUrl: null,
    featured: false,
    featuredOrder: null,
    engine: "4.5L M117 V8",
    transmission: "3-Speed Automatic",
    horsepower: 180,
    torque: "220 lb-ft",
    drivetrain: "RWD",
    topSpeed: "124 mph",
    zeroToSixty: "10.5 s",
    fuelType: "Gasoline",
    bodyStyle: "Roadster",
    productionNumbers: "66,298 (1971–1980)",
    marketValue: "$30,000 – $48,000",
    historyEvents: history("v-450sl-1978", [
      { date: "1978", type: "sale", title: "Sold new", detail: "Delivered new, Scottsdale, AZ", source: "Dealer records" },
      { date: "1978", type: "title", title: "Title issued — Clean", detail: "Arizona", source: "DMV records" },
      { date: "1994", type: "accident", severity: "minor", title: "Minor accident reported", detail: "Rear bumper impact at low speed. Bumper and right rear quarter trim replaced; no airbag deployment, no frame damage.", mileage: 61500, source: "Carfax" },
      { date: "2002", type: "sale", title: "Second family ownership", detail: "Sold within extended family, remained in Arizona", source: "Title transfer" },
      { date: "2016-02-11", type: "sale", title: "Acquired by The Lara Collection", detail: "Current ownership", mileage: 99800, source: "Collection records" },
      { date: "2021-05-14", type: "service", title: "Climate control overhaul", detail: "A/C converted and serviced, timing chain inspected", mileage: 101900, source: "Service file" },
    ]),
  }),
  vehicle({
    id: "v-560sl-1987",
    slug: "1987-mercedes-benz-560sl",
    brand: "mercedes",
    year: 1987,
    make: "Mercedes-Benz",
    model: "560SL",
    chassisCode: "R107",
    vin: "WDBBA48D8HAXXXXXX",
    color: "Signal Red",
    interiorColor: "Palomino Leather",
    mileage: 58900,
    currentOwner: OWNER,
    purchaseDate: "2013-10-30",
    purchasePrice: 27000,
    estimatedValue: 62000,
    numOwners: 2,
    titleStatus: "Clean",
    carfaxStatus: "Clean — No Accidents Reported",
    location: LOCATION,
    story: `The 560SL was the R107's send-off — the most powerful, most refined, and most complete version of a car that had already been on sale for fifteen years. The final-generation cars are now the most sought-after of the line.

This Signal Red over Palomino example is a two-owner car with books, both tops, and a complete service file from new. The collection considers it the best-preserved R107 it has encountered.`,
    rotatingVideoUrl: null,
    heroImageUrl: null,
    featured: false,
    featuredOrder: null,
    engine: "5.5L M117 V8",
    transmission: "4-Speed Automatic",
    horsepower: 227,
    torque: "279 lb-ft",
    drivetrain: "RWD",
    topSpeed: "137 mph",
    zeroToSixty: "7.5 s",
    fuelType: "Gasoline",
    bodyStyle: "Roadster",
    productionNumbers: "49,347 (1986–1989)",
    marketValue: "$45,000 – $75,000",
  }),
  vehicle({
    id: "v-glk350-2011",
    slug: "2011-mercedes-benz-glk350",
    brand: "mercedes",
    year: 2011,
    make: "Mercedes-Benz",
    model: "GLK350",
    chassisCode: "X204",
    vin: "WDCGG8HB7AFXXXXXX",
    color: "Steel Grey Metallic",
    interiorColor: "Black MB-Tex",
    mileage: 87600,
    currentOwner: OWNER,
    purchaseDate: "2011-04-09",
    purchasePrice: 41000,
    estimatedValue: 14000,
    numOwners: 1,
    titleStatus: "Clean",
    carfaxStatus: "Clean — One Owner",
    location: LOCATION,
    story: `Every collection needs a workhorse. The GLK350 was bought new in 2011 and has served as the collection's support vehicle ever since — parts runs, event logistics, winter duty.

One owner from new, every service on schedule. It will never be the star of the garage, but nothing in the garage moves without it.`,
    rotatingVideoUrl: null,
    heroImageUrl: null,
    featured: false,
    featuredOrder: null,
    engine: "3.5L M272 V6",
    transmission: "7-Speed Automatic",
    horsepower: 268,
    torque: "258 lb-ft",
    drivetrain: "4MATIC AWD",
    topSpeed: "130 mph (limited)",
    zeroToSixty: "6.5 s",
    fuelType: "Gasoline",
    bodyStyle: "SUV",
    productionNumbers: "Series production",
    marketValue: "$10,000 – $16,000",
  }),

  // ───────────────────────── PORSCHE ─────────────────────────
  vehicle({
    id: "v-356-1963",
    slug: "1963-porsche-356-cabriolet",
    brand: "porsche",
    year: 1963,
    make: "Porsche",
    model: "356 Cabriolet",
    chassisCode: "356B T6",
    vin: "15XXXX",
    color: "Slate Grey",
    interiorColor: "Red Leather",
    mileage: 74200,
    currentOwner: OWNER,
    purchaseDate: "2010-08-21",
    purchasePrice: 105000,
    estimatedValue: 185000,
    numOwners: 5,
    titleStatus: "Clean",
    carfaxStatus: "Pre-Carfax Era — Kardex Documented",
    location: LOCATION,
    story: `Before the 911, there was this — the car that made Porsche, Porsche. The 356 Cabriolet pairs Erwin Komenda's timeless body with an air-cooled simplicity that still defines the marque's character.

This 1963 356B is a Super 90 Cabriolet in Slate Grey over red, with its Kardex confirming matching numbers and original colours. It was the first Porsche acquired by the collection and remains its sentimental cornerstone.`,
    rotatingVideoUrl: null,
    heroImageUrl: null,
    engineSoundUrl: "/audio/1963-porsche-356-cabriolet-engine.mp3",
    featured: true,
    featuredOrder: 2,
    engine: "1.6L Air-Cooled Flat-4 (Super 90)",
    transmission: "4-Speed Manual",
    horsepower: 90,
    torque: "89 lb-ft",
    drivetrain: "RWD",
    topSpeed: "110 mph",
    zeroToSixty: "12.7 s",
    fuelType: "Gasoline",
    bodyStyle: "Cabriolet",
    productionNumbers: "Approx. 76,300 (all 356, 1948–1965)",
    marketValue: "$160,000 – $220,000",
  }),
  vehicle({
    id: "v-930-1988",
    slug: "1988-porsche-911-turbo-coupe-930",
    brand: "porsche",
    year: 1988,
    make: "Porsche",
    model: "911 Turbo Coupe (930)",
    chassisCode: "930",
    vin: "WP0JB0939JS05XXXX",
    color: "Grand Prix White",
    interiorColor: "Black Leather",
    mileage: 41700,
    currentOwner: OWNER,
    purchaseDate: "2014-09-12",
    purchasePrice: 98000,
    estimatedValue: 175000,
    numOwners: 3,
    titleStatus: "Clean",
    carfaxStatus: "Clean — No Accidents Reported",
    location: LOCATION,
    story: `The Widowmaker. The 930 earned its reputation honestly — 282 turbocharged horsepower, a four-speed gearbox, and all of the engine hung behind the rear axle. It demanded respect and rewarded it with an experience nothing modern can replicate.

This 1988 coupe in Grand Prix White is a three-owner, accident-free car with the desirable factory limited-slip differential. The whale tail, the bulging arches, the lag and then the surge — this is the definitive 1980s supercar.`,
    rotatingVideoUrl: null,
    heroImageUrl: null,
    engineSoundUrl: "/audio/1988-porsche-911-turbo-coupe-930-engine.mp3",
    featured: true,
    featuredOrder: 3,
    engine: "3.3L Turbocharged Flat-6",
    transmission: "4-Speed Manual",
    horsepower: 282,
    torque: "278 lb-ft",
    drivetrain: "RWD",
    topSpeed: "161 mph",
    zeroToSixty: "5.0 s",
    fuelType: "Gasoline",
    bodyStyle: "Coupe",
    productionNumbers: "Approx. 21,589 (930, 1975–1989)",
    marketValue: "$150,000 – $200,000",
    historyEvents: history("v-930-1988", [
      { date: "1988", type: "sale", title: "Sold new", detail: "Delivered new, Chicago, IL — factory limited-slip differential", source: "Porsche COA" },
      { date: "1988", type: "title", title: "Title issued — Clean", detail: "Illinois", source: "DMV records" },
      { date: "1996", type: "sale", title: "Second owner", detail: "Collector purchase, climate-controlled storage", mileage: 18200, source: "Carfax" },
      { date: "2014-09-12", type: "sale", title: "Acquired by The Lara Collection", detail: "Current ownership — accident-free history verified", mileage: 39600, source: "Collection records" },
      { date: "2019-06-21", type: "service", title: "Top-end engine service", detail: "Valve guides, turbocharger resealed, new fuel lines", mileage: 40800, source: "Service file" },
      { date: "2024-08-15", type: "inspection", title: "Pre-purchase-grade inspection", detail: "Paint meter readings factory-original on all panels except front bumper (stone-chip respray)", mileage: 41700, source: "Independent appraiser" },
    ]),
  }),
  vehicle({
    id: "v-993turbo-1997",
    slug: "1997-porsche-911-turbo-coupe",
    brand: "porsche",
    year: 1997,
    make: "Porsche",
    model: "911 Turbo Coupe",
    chassisCode: "993",
    vin: "WP0AC2999VS37XXXX",
    color: "Arena Red Metallic",
    interiorColor: "Black Leather",
    mileage: 36800,
    currentOwner: OWNER,
    purchaseDate: "2016-11-19",
    purchasePrice: 145000,
    estimatedValue: 265000,
    numOwners: 4,
    titleStatus: "Clean",
    carfaxStatus: "Clean — No Accidents Reported",
    location: LOCATION,
    story: `The last air-cooled Turbo — and for many, the greatest 911 of them all. The 993 Turbo introduced twin turbochargers and all-wheel drive, taming the Widowmaker's manners without losing its violence.

This Arena Red 1997 coupe is a low-mileage example with full service history. Values of the 993 Turbo have reflected what enthusiasts always knew: this is the air-cooled era's final, finest statement.`,
    rotatingVideoUrl: null,
    heroImageUrl: null,
    featured: false,
    featuredOrder: null,
    engine: "3.6L Twin-Turbo Flat-6",
    transmission: "6-Speed Manual",
    horsepower: 402,
    torque: "398 lb-ft",
    drivetrain: "AWD",
    topSpeed: "180 mph",
    zeroToSixty: "3.7 s",
    fuelType: "Gasoline",
    bodyStyle: "Coupe",
    productionNumbers: "Approx. 5,978 (993 Turbo)",
    marketValue: "$230,000 – $300,000",
  }),
  vehicle({
    id: "v-macan-2016",
    slug: "2016-porsche-macan-turbo",
    brand: "porsche",
    year: 2016,
    make: "Porsche",
    model: "Macan Turbo",
    chassisCode: "95B",
    vin: "WP1AF2A5XGLB9XXXX",
    color: "Jet Black Metallic",
    interiorColor: "Black/Garnet Red Leather",
    mileage: 52300,
    currentOwner: OWNER,
    purchaseDate: "2016-01-15",
    purchasePrice: 84000,
    estimatedValue: 42000,
    numOwners: 1,
    titleStatus: "Clean",
    carfaxStatus: "Clean — One Owner",
    location: LOCATION,
    story: `The daily. Bought new in 2016, the Macan Turbo proved that Porsche could build a family car that still felt like a Porsche — 400 horsepower and genuine steering feel in a school-run silhouette.

One owner, full Porsche dealer history. It is the collection's most-used vehicle and, mile for mile, perhaps its most loved.`,
    rotatingVideoUrl: null,
    heroImageUrl: null,
    featured: false,
    featuredOrder: null,
    engine: "3.6L Twin-Turbo V6",
    transmission: "7-Speed PDK",
    horsepower: 400,
    torque: "406 lb-ft",
    drivetrain: "AWD",
    topSpeed: "165 mph",
    zeroToSixty: "4.4 s",
    fuelType: "Gasoline",
    bodyStyle: "SUV",
    productionNumbers: "Series production",
    marketValue: "$35,000 – $48,000",
    historyEvents: history("v-macan-2016", [
      { date: "2016-01-15", type: "sale", title: "Sold new", detail: "Delivered new to The Lara Collection", source: "Dealer records" },
      { date: "2016-01-15", type: "title", title: "Title issued — Clean", detail: "One owner from new", source: "DMV records" },
      { date: "2018-03-22", type: "recall", title: "Factory recall completed", detail: "Fuel pump flange replacement performed under recall at Porsche dealer", mileage: 21400, source: "Porsche service record" },
      { date: "2022-10-05", type: "service", title: "Major service", detail: "PDK fluid, brakes, all four tires", mileage: 44100, source: "Porsche service record" },
    ]),
  }),
  vehicle({
    id: "v-targa-2022",
    slug: "2022-porsche-911-targa-4-gts",
    brand: "porsche",
    year: 2022,
    make: "Porsche",
    model: "911 Targa 4 GTS",
    chassisCode: "992",
    vin: "WP0BB2A93NS23XXXX",
    color: "GT Silver Metallic",
    interiorColor: "Black/Mojave Beige",
    mileage: 8900,
    currentOwner: OWNER,
    purchaseDate: "2022-03-04",
    purchasePrice: 162000,
    estimatedValue: 178000,
    numOwners: 1,
    titleStatus: "Clean",
    carfaxStatus: "Clean — One Owner",
    location: LOCATION,
    story: `The Targa is the 911 at its most romantic — the signature hoop a direct line back to 1965, the year of the collection's first Pagoda. The 992 Targa 4 GTS pairs that silhouette with 473 horsepower and a roof mechanism that is pure theatre.

Ordered new in GT Silver with the seven-speed manual's PDK sibling, this car bridges the collection's classic and modern eras — it is the car that gets driven when the destination matters as much as the road.`,
    rotatingVideoUrl: null,
    heroImageUrl: null,
    featured: false,
    featuredOrder: null,
    engine: "3.0L Twin-Turbo Flat-6",
    transmission: "8-Speed PDK",
    horsepower: 473,
    torque: "420 lb-ft",
    drivetrain: "AWD",
    topSpeed: "190 mph",
    zeroToSixty: "3.4 s",
    fuelType: "Gasoline",
    bodyStyle: "Targa",
    productionNumbers: "Series production",
    marketValue: "$165,000 – $195,000",
  }),
  vehicle({
    id: "v-gt4rs-2023",
    slug: "2023-porsche-718-cayman-gt4-rs",
    brand: "porsche",
    year: 2023,
    make: "Porsche",
    model: "718 Cayman GT4 RS",
    chassisCode: "982",
    vin: "WP0AE2A85PK27XXXX",
    color: "Arctic Grey",
    interiorColor: "Black/Race-Tex",
    mileage: 3400,
    currentOwner: OWNER,
    purchaseDate: "2023-05-26",
    purchasePrice: 198000,
    estimatedValue: 215000,
    numOwners: 1,
    titleStatus: "Clean",
    carfaxStatus: "Clean — One Owner",
    location: LOCATION,
    story: `The GT4 RS is the car Porsche's GT division was never supposed to build — the 911 GT3's 9,000 rpm flat-six dropped into the smaller, mid-engined Cayman. The result is the most visceral road car of its generation.

This Arctic Grey example wears the Weissach Package and magnesium wheels. The intake ducts where rear windows should be deliver the induction noise directly to the driver's ears. Nothing else in the collection sounds like it. Nothing else anywhere sounds like it.`,
    rotatingVideoUrl: null,
    heroImageUrl: null,
    engineSoundUrl: "/audio/2023-porsche-718-cayman-gt4-rs-engine.mp3",
    featured: false,
    featuredOrder: null,
    engine: "4.0L Naturally-Aspirated Flat-6",
    transmission: "7-Speed PDK",
    horsepower: 493,
    torque: "331 lb-ft",
    drivetrain: "RWD",
    topSpeed: "196 mph",
    zeroToSixty: "3.2 s",
    fuelType: "Gasoline",
    bodyStyle: "Coupe",
    productionNumbers: "Limited production",
    marketValue: "$195,000 – $235,000",
  }),
  vehicle({
    id: "v-turbos-2024",
    slug: "2024-porsche-911-turbo-s",
    brand: "porsche",
    year: 2024,
    make: "Porsche",
    model: "911 Turbo S",
    chassisCode: "992",
    vin: "WP0AD2A91RS25XXXX",
    color: "Jet Black Metallic",
    interiorColor: "Black/Bordeaux Red",
    mileage: 1850,
    currentOwner: OWNER,
    purchaseDate: "2024-02-16",
    purchasePrice: 246000,
    estimatedValue: 252000,
    numOwners: 1,
    titleStatus: "Clean",
    carfaxStatus: "Clean — One Owner",
    location: LOCATION,
    story: `Thirty-six years separate this car from the collection's 930 — and the lineage is unbroken. The 992 Turbo S is the modern expression of the same idea: the everyday 911, turbocharged beyond reason.

640 horsepower, 2.6 seconds to sixty, and the composure of a luxury sedan. It is the newest car in the collection and its chronological bookend — the "new" in a story that runs from 1958 to 2024.`,
    rotatingVideoUrl: "/videos/2024-porsche-911-turbo-s-rotating.mp4",
    heroImageUrl: null,
    engineSoundUrl: "/audio/2024-porsche-911-turbo-s-engine.mp3",
    featured: true,
    featuredOrder: 4,
    engine: "3.7L Twin-Turbo Flat-6",
    transmission: "8-Speed PDK",
    horsepower: 640,
    torque: "590 lb-ft",
    drivetrain: "AWD",
    topSpeed: "205 mph",
    zeroToSixty: "2.6 s",
    fuelType: "Gasoline",
    bodyStyle: "Coupe",
    productionNumbers: "Series production",
    marketValue: "$235,000 – $265,000",
  }),

  // ───────────────────────── FERRARI ─────────────────────────
  vehicle({
    id: "v-458-2015",
    slug: "2015-ferrari-458-spider",
    brand: "ferrari",
    year: 2015,
    make: "Ferrari",
    model: "458 Spider",
    chassisCode: "F142",
    vin: "ZFF68NHA3F020XXXX",
    color: "Rosso Corsa",
    interiorColor: "Crema Leather",
    mileage: 11200,
    currentOwner: OWNER,
    purchaseDate: "2018-04-13",
    purchasePrice: 235000,
    estimatedValue: 310000,
    numOwners: 2,
    titleStatus: "Clean",
    carfaxStatus: "Clean — No Accidents Reported",
    location: LOCATION,
    story: `The 458 Spider is the end of an era — the last mid-engined Ferrari V8 to breathe without turbochargers. Its 4.5-litre engine spins to 9,000 rpm with a sound that no forced-induction successor has matched.

This Rosso Corsa over Crema example is a two-owner car with full Ferrari Classiche eligibility, factory carbon trim, and the retractable hardtop that made the Spider an engineering landmark. It is the only Ferrari in the collection, and the collection believes the right Ferrari needs no company.`,
    rotatingVideoUrl: null,
    heroImageUrl: null,
    engineSoundUrl: "/audio/2015-ferrari-458-spider-engine.mp3",
    featured: true,
    featuredOrder: 5,
    engine: "4.5L Naturally-Aspirated V8",
    transmission: "7-Speed Dual-Clutch",
    horsepower: 562,
    torque: "398 lb-ft",
    drivetrain: "RWD",
    topSpeed: "199 mph",
    zeroToSixty: "3.4 s",
    fuelType: "Gasoline",
    bodyStyle: "Spider",
    productionNumbers: "Approx. 5,800 (458 Spider)",
    marketValue: "$280,000 – $340,000",
    historyEvents: history("v-458-2015", [
      { date: "2015-03-18", type: "sale", title: "Sold new", detail: "Delivered new, Ferrari of Newport Beach, CA", source: "Ferrari records" },
      { date: "2015-03-18", type: "title", title: "Title issued — Clean", detail: "California", source: "DMV records" },
      { date: "2016-04-02", type: "service", title: "Annual service", detail: "Ferrari main dealer, all fluids and inspections", mileage: 3100, source: "Carfax" },
      { date: "2017-04-20", type: "service", title: "Annual service", detail: "Ferrari main dealer", mileage: 6400, source: "Carfax" },
      { date: "2018-04-13", type: "sale", title: "Acquired by The Lara Collection", detail: "Current ownership — Classiche eligibility verified", mileage: 8200, source: "Collection records" },
      { date: "2024-05-09", type: "inspection", title: "Carfax report — no accidents or damage reported", detail: "Two owners, no open recalls, mileage consistent", mileage: 11200, source: "Carfax" },
    ]),
  }),
];

export const HERO_VIDEO_URL = "/videos/hero-old-to-new-v2.mp4";
export const SIGNATURE_URL = "/images/signature.png";
